### ISSUE TITLE
Is there any way to generate copy button when using  rehype-highlight-code-block ?

### ISSUE THREAD

**Issue by ideaviewes** [mapbox/rehype-highlight-code-block#2]
Is there any way to generate copy button when using  rehype-highlight-code-block ?

**Comment by wooorm** [comment]
All of this happens “server side”. Copy buttons need client side JS anyway, and can’t work without JS. So it’s better to solve it on your side that trying to add that here.

**Comment by ideaviewes** [comment]
Thank you
but after the html generated,It is really difficult to change the structure and The code block also mix with html tags.
To implement this function on client side is too hard。
I use nextjs to build my website,and rehype to render markdown contents.
Is there any way to solve this problem?

**Comment by wooorm** [comment]
There are tons of ways to solve this.
But I don’t believe it’s not something for this project, as I mentioned before.
If you use rehype, you can write a plugin.
I don’t see why it’s hard to change HTML after this plugin. The code blocks are still there. You can append into them. Either with a rehype plugin, or with client-side JavaScript (which is a good place for buttons that only do client-side JavaScript-things!)

**Comment by ideaviewes** [comment]
@wooorm ,ok
